### ISSUE TITLE
Error when trying to select any video

### ISSUE THREAD

**Issue by theTaskManagerGaming** [TheLogicMaster/SDH-AnimationChanger#26] opened 2022-11-07 16:53 UTC
Hello, I am having an issue with AnimationChanger. I was able to use it for a few hours with no issues then it has started displaying this error overlay when selecting ANY video. The blurry message can only be removed if I Restart Steam or Reboot the Deck. I have removed the app multiple times, changed from Stable, to Beta, to Preview in SteamOS. I have removed Decky Loader, removed all files related to either app. I am at a loss. I have 2.3.2-pre1 of Decky installed and 1.2.0 of AnimationChanger. I have attached a screenshot of what it is doing.

Thanks
![SD-Ani-Error](https://user-images.githubusercontent.com/117670456/200366641-0d34edc4-46f1-4d92-aae2-78942f8031ad.jpg)

**Comment by TheLogicMaster** [comment] 2022-11-07 17:13
Should be fixed in 1.2.1

**Comment by BlackRabbit22** [comment] 2022-11-12 21:00
@TheLogicMaster still having the issue in 1.2.1

**Comment by miltoid19** [comment] 2022-11-13 13:43
Had the same problem. Fixed by getting into desktop mode and then doing a full reboot form there.

**Comment by TheLogicMaster** [comment] 2022-11-13 23:53
> Had the same problem. Fixed by getting into desktop mode and then doing a full reboot form there.

Was this a one time issue after updating or is it a reoccurring thing?

**Comment by seriosbrad** [comment] 2022-11-14 20:36
Full-rebooting from desktop mode fixed it.  I applied some animations and restarted normally from SteamOS and it's still fixed.  I can't say for sure that it's permanently fixed though, too soon to say I guess.

**Comment by miltoid19** [comment] 2022-11-15 17:55
> > Had the same problem. Fixed by getting into desktop mode and then doing a full reboot form there.
> 
> Was this a one time issue after updating or is it a reoccurring thing?

I can confirm it was a one-time issue after the reboot from desktop it is fixed

**Comment by numbawon** [comment] 2022-12-12 22:45
I'm having this same issue. But at least for me, rebooting from desktop isn't fixing it. I'm currently running deck-loader v2.4.6-pre3 (also tested on stable build of decky v2.4.5) on SteamDeck os 3.3.2 beta channel build#20221005.1 as well as Animation changer 1.2.1,but had same results with 1.2.0 as well. Also when I get that overlay, it continues to cover the screen image, but it seems to allow you to somewhat travel around underneath the overlay.

Right now, I've been testing on boot I'll qam to decky loader > Animation Changer > click on the videos in the top row immediately, and get covered by the overlay. Then click and hold the power button to get to desktop mode, then once in desktop mode reboot. I've rebooted by cli and by gui and same result either way, when I load back in and get to Animation Changer and click on a video to preview I still get the overlay.

On one cycle through, in frustration, I rapidly hit the "A" button and it actually stacked the overlay till it was more dark and obscure. So there is that too, a bug within a bug...

**Comment by numbawon** [comment] 2022-12-13 02:31
@TheLogicMaster thanks for the update. That looks exactly it. I assume nobody has found any other work around probably?

**Comment by TheLogicMaster** [comment] 2022-12-13 04:01
> @TheLogicMaster thanks for the update. That looks exactly it. I assume nobody has found any other work around probably? 

Probably just needs the underlying issue to be fixed in the frontend lib, since it's a problem with all dialog windows, most likely. If the other Dialogs used in Decky work now, then it has probably been patched already and I just need to bump the version and update the plugin. Haven't had an opportunity to test yet, I'll probably check it out tomorrow.

**Comment by TheLogicMaster** [comment] 2022-12-14 21:59
Tested with the newest front-end library and the modal window issue persists, so it will probably take a bit of debugging to figure out.

**Comment by TheLogicMaster** [comment] 2022-12-19 02:55
Fixed in 1.2.2

**Closed** 2023-05-02 21:18 UTC
